## code to prepare `config` dataset goes here




config_db <- list(
    # access_mode = "automatic",
    allocator_background_threads = "false",
    allocator_bulk_deallocation_flush_threshold = "512MB",
    allocator_flush_threshold = "128MB",
    allow_community_extensions = "true",
    allow_extensions_metadata_mismatch = "false",
    allow_persistent_secrets = "true",
    allow_unredacted_secrets = "false",
    allow_unsigned_extensions = "false",
    # allowed_directories = "[]",
    # allowed_paths = "[]",
    arrow_large_buffer_size = "false",
    arrow_lossless_conversion = "false",
    arrow_output_list_view = "false",
    autoinstall_extension_repository = "",
    autoinstall_known_extensions = "true",
    autoload_known_extensions = "true",
    # binary_as_string = "false",
    ca_cert_file = "",
    catalog_error_max_schemas = "100",
    checkpoint_threshold = "16MB",
    wal_autocheckpoint = "16MB",
    custom_extension_repository = "",
    # custom_user_agent = "",
    default_block_size = "262144",
    default_collation = "",
    default_null_order = "NULLS_LAST",
    null_order = "NULLS_LAST",
    default_order = "ASC",
    default_secret_storage = "local_file",
    # disable_parquet_prefetching = "false",
    disabled_compression_methods = "",
    # disabled_filesystems = "",
    # disabled_log_types = "",
    # duckdb_api = "cli",
    # enable_external_access = "true",
    enable_external_file_cache = "true",
    enable_fsst_vectors = "false",
    # enable_geoparquet_conversion = "true",
    enable_http_metadata_cache = "false",
    # enable_logging = "false",
    enable_macro_dependencies = "false",
    enable_object_cache = "false",
    enable_server_cert_verification = "false",
    enable_view_dependencies = "false",
    # enabled_log_types = "",
    extension_directory = "",
    external_threads = "1",
    force_download = "false",
    # http_keep_alive = "true",
    # http_proxy = "",
    # http_proxy_password = "",
    # http_proxy_username = "",
    # http_retries = "3",
    # http_retry_backoff = "4",
    # http_retry_wait_ms = "100",
    # http_timeout = "30",
    immediate_transaction_mode = "false",
    index_scan_max_count = "2048",
    index_scan_percentage = "0.001",
    lock_configuration = "false",
    # logging_level = "INFO",
    # logging_mode = "LEVEL_ONLY",
    # logging_storage = "memory",
    # max_memory = "2GB",  # or something like "2GB"
    # memory_limit = "2GB",
    # max_temp_directory_size = "90%",
    max_vacuum_tasks = "100",
    old_implicit_casting = "false",
    parquet_metadata_cache = "false",
    # password = "",
    # prefetch_all_parquet_files = "false",
    preserve_insertion_order = "true",
    produce_arrow_string_view = "false",
    # s3_access_key_id = "",
    # s3_endpoint = "",
    # s3_kms_key_id = "",
    # s3_region = "us-east-1",
    # s3_secret_access_key = "",
    # s3_session_token = "",
    # s3_uploader_max_filesize = "800GB",
    # s3_uploader_max_parts_per_file = "10000",
    # s3_uploader_thread_limit = "50",
    # s3_url_compatibility_mode = "false",
    # s3_url_style = "vhost",
    # s3_use_ssl = "true",
    scheduler_process_partial = "false",
    secret_directory = "~/.duckdb/stored_secrets",
    storage_compatibility_version = "v0.10.2",
    temp_directory = "",
    threads = "4",
    worker_threads = "4",
    username = "",
    user = "",
    zstd_min_string_length = "4096"

    # Local/session config options:
    # custom_profiling_settings = "",
    # enable_http_logging = "false",
    # enable_profiling = "",
    # enable_progress_bar_print = "true",
    # enable_progress_bar = "true",
    # errors_as_json = "false"
)




usethis::use_data(config_db, overwrite = TRUE)
